"""Add clear screen7

Revision ID: 00f892cca061
Revises: 076473abfc1a
Create Date: 2023-06-08 21:17:06.687653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f892cca061'
down_revision = '076473abfc1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
