"""Add clear screen6

Revision ID: 076473abfc1a
Revises: 5864dfa01c56
Create Date: 2023-06-08 21:11:41.430375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076473abfc1a'
down_revision = '5864dfa01c56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
