"""Add clear screen2

Revision ID: 3fd8113b0b31
Revises: 6a4311fa5cba
Create Date: 2023-06-08 11:47:37.686996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd8113b0b31'
down_revision = '6a4311fa5cba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
