"""Add clear screen4

Revision ID: 571756bf6422
Revises: f9edba954082
Create Date: 2023-06-08 11:53:03.861041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571756bf6422'
down_revision = 'f9edba954082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
