"""Add clear screen6

Revision ID: 5864dfa01c56
Revises: 63e841f04c85
Create Date: 2023-06-08 21:08:07.976902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5864dfa01c56'
down_revision = '63e841f04c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
