"""Add clear screen5

Revision ID: 63e841f04c85
Revises: 571756bf6422
Create Date: 2023-06-08 21:06:01.919525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e841f04c85'
down_revision = '571756bf6422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
