"""Add clear screen

Revision ID: 6a4311fa5cba
Revises: 5a3a1d5b7e36
Create Date: 2023-06-08 11:44:41.936305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4311fa5cba'
down_revision = '5a3a1d5b7e36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
