"""Add clear screen3

Revision ID: f9edba954082
Revises: 3fd8113b0b31
Create Date: 2023-06-08 11:48:49.736818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9edba954082'
down_revision = '3fd8113b0b31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
